In [2]:
import numpy as np
import pandas as pd

In [4]:
covid = pd.read_csv('yelp_covid.csv', index_col=0)
covid

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,delivery_service,virtual_services_offered
0,UxhEJdt0iacusZP1gmNZAg,Belleville Ale House,7 W Main St,Belleville,WI,53508,42.859856,-89.534448,3.5,9,No,FALSE
1,7vf9ldE1dRYvFvu1kr1bOg,Borland's Tavern,119 W Main St,Belleville,WI,53508,42.859919,-89.535941,4.0,15,Yes,FALSE
2,SuvUcBB1FQsIMGehM7fC2A,Cameo Rose Victorian Country Inn,1090 Severson Rd,Belleville,WI,53508,42.916459,-89.496173,5.0,5,No,FALSE
3,xBbOm9WudqW85x58IWiXdg,Charlie's Bark Park - Belleville,350 Enterprise Ave,Belleville,WI,53508,42.861565,-89.528715,3.5,12,No,FALSE
4,yfJcj4qwewXp_QJ7L5WMfw,Corner Cafe,30 W Main St,Belleville,WI,53508,42.859459,-89.535057,2.5,6,Yes,FALSE
...,...,...,...,...,...,...,...,...,...,...,...,...
198273,bs3sGDi1bf_-4xATryW8WQ,Walmart,35 Sage Hill Gate NW,Sage Hill,AB,T3R 0S4,51.169821,-114.142211,2.5,5,No,FALSE
198274,dWju7gfRvVAjj22Eah2zfA,Le Feu de Bois,1126 Boulevard Sainte Adèle,Sainte-Adèle,AB,J8B 2N6,45.952061,-74.135853,4.5,8,Yes,FALSE
198275,2Ftldk_cKZfMjNoEuv7tNg,Great Clips,Walden Gate,Southeast Calgary,AB,T0L 0X0,50.875808,-114.035726,2.0,5,No,FALSE
198276,HFUxm92v6bPI9JB_-lj9bw,Pet Planet,Walden Gate,Southeast Calgary,AB,T0L 0X0,50.875808,-114.035726,4.5,3,No,FALSE
198277,kUIQabW7lPJfzhhmlGpj4A,The Brass Monkey,950 Queensland Drive SE,Southeast Calgary,AB,T2J 5E5,50.932679,-114.017339,5.0,3,Yes,FALSE

In [7]:
state_stars_average = covid.groupby('state')['stars'].mean()
state_stars_average

state
AB    3.331436
AK    2.500000
AL    3.833333
AR    3.500000
AZ    3.611526
BC    1.500000
CA    3.214286
CO    2.250000
CT    4.000000
FL    3.000000
GA    3.750000
HI    2.000000
IL    3.380586
MB    4.000000
MI    3.500000
MO    2.500000
NC    3.483618
NE    2.750000
NV    3.619417
NY    3.214286
OH    3.453571
ON    3.323424
OR    2.500000
PA    3.542366
QC    3.607401
SC    3.458819
TX    3.083333
UT    2.500000
VA    1.500000
VT    4.000000
WA    2.250000
WI    3.562079
Name: stars, dtype: float64

In [9]:
n_states_greater = (state_stars_average > state_stars_average['CA']).sum()
n_states_greater

18

In [11]:
covid.groupby('stars')['review_count'].std()
# From inspection below, stars 4.0 has the max std dev

stars
1.0     10.653897
1.5     48.332271
2.0     45.745526
2.5     79.272118
3.0     99.702662
3.5    122.041768
4.0    191.829207
4.5    153.090426
5.0     37.370870
Name: review_count, dtype: float64

In [19]:
df_10k = pd.read_csv('10k_sample.csv')
df_10k

,cik,year,name,item_1_text,gvkey,raw_length
0,1753886,2020,Stonemor Inc.,OVERVIEW Our History We were formed as a Delaw...,160207,5310
1,1606498,2020,"Avanos Medical, Inc.","Overview Avanos Medical, Inc. is a medical tec...",21352,3628
2,1050825,2020,STEELCASE INC,The following business overview is qualified i...,66290,3634
3,885275,2020,WILSON BANK HOLDING CO,General Wilson Bank Holding Company (the Comp...,264731,12648
4,1169561,2020,COMMVAULT SYSTEMS INC,Company Overview Commvault is a leading provid...,174077,6010
...,...,...,...,...,...,...
495,1275014,2020,"Ultra Clean Holdings, Inc.","Overview Ultra Clean Holdings, Inc., ( UCT , t...",264416,5847
496,717720,2020,VALUE LINE INC,"Value Line, Inc. is a New York corporation hea...",11099,5648
497,1533615,2020,Global Medical REIT Inc.,Organization Global Medical REIT Inc. (the Co...,16125,6120
498,1722010,2020,OP Bancorp,Our Company We are a bank holding company head...,164395,18357
499,706863,2020,UNION BANKSHARES INC,Certain Definitions: Capitalized terms used in...,111537,7686

In [20]:
# reusing code from class08 notebooks to clean text
import string
translator = str.maketrans('', '', string.punctuation)
df_10k['item1'] = df_10k['item_1_text'].apply(lambda s: s.lower().translate(translator))
df_10k['wc'] = df_10k['item1'].apply(lambda s: len(s.split()))
df_10k[df_10k['wc'] == df_10k['wc'].max()]

,cik,year,name,item_1_text,gvkey,raw_length,item1,wc
83,1773751,2020,Oaktree Acquisition Corp.,a leading global investment management firm he...,37851,37115,a leading global investment management firm he...,37106

In [21]:
df_10k['slsts'] = df_10k['item_1_text'].apply(lambda s: s.split('.'))
df_10k['avg_slen'] = df_10k['slsts'].apply(lambda lsts: sum(len(s) for s in lsts)/len(lsts))
round(df_10k['avg_slen'].mean())

151

In [23]:
# reusing code from class08 notebooks to clean text
import nltk
nltk.download('stopwords')
eng_stopwords = set(nltk.corpus.stopwords.words('english'))
df_10k['item1c'] = df_10k['item1'].apply(lambda s: [w for w in s.split() if w not in eng_stopwords])
df_10k['wc1'] = df_10k['item1c'].apply(lambda lst: len(lst))
df_10k[df_10k['wc1'] == df_10k['wc1'].min()]

[nltk_data] Downloading package stopwords to /home/jl/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,cik,year,name,item_1_text,gvkey,raw_length,item1,wc,slsts,avg_slen,item1c,wc1
95,886982,2020,GOLDMAN SACHS GROUP INC,Cautionary Statement Pursuant to the U.S. Priv...,114628,13,cautionary statement pursuant to the us privat...,13,"[Cautionary Statement Pursuant to the U, S, P...",29.333333,"[cautionary, statement, pursuant, us, private,...",10

In [25]:
df_10k['bwp'] = df_10k['item1c'].apply(lambda lst: sum(len(w) >= 7 for w in lst) / len(lst))
df_10k[df_10k['bwp'] == df_10k['bwp'].max()]

,cik,year,name,item_1_text,gvkey,raw_length,item1,wc,slsts,avg_slen,item1c,wc1,bwp
361,847942,2020,STRATEGIC ACQUISITIONS INC /NV/,"Strategic Acquisitions, Inc. (the Company or...",23369,3501,strategic acquisitions inc the company or s...,3498,"[Strategic Acquisitions, Inc, (the Company ...",219.067308,"[strategic, acquisitions, inc, company, strate...",1844,0.70987

In [38]:
# How to check if col val contains a substring
# ref: https://stackoverflow.com/questions/30944577/check-if-string-is-in-a-pandas-dataframe
df_10k['item1s'] = df_10k['item1c'].apply(lambda lst: ' '.join(lst))
df_10k['ai_count'] = df_10k['item1c'].apply(lambda lst: sum(w == 'ai' for w in lst)) 
(df_10k['ai_count'] > 0 | df_10k['item1s'].str.contains('deep learning')).sum()

18

In [39]:
crime = pd.read_csv('crime.csv')
crime

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y,Latitude,Longitude
0,Theft from Vehicle,2016,8,15,18.0,0.0,8XX SEYMOUR ST,Central Business District,491251.16,5458553.29,49.279672,-123.120289
1,Theft from Vehicle,2016,8,15,18.0,30.0,8XX SEYMOUR ST,Central Business District,491251.16,5458553.29,49.279672,-123.120289
2,Theft from Vehicle,2016,9,3,8.0,0.0,8XX SEYMOUR ST,Central Business District,491251.16,5458553.29,49.279672,-123.120289
3,Theft from Vehicle,2016,9,15,9.0,0.0,8XX SEYMOUR ST,Central Business District,491251.16,5458553.29,49.279672,-123.120289
4,Theft from Vehicle,2016,10,13,19.0,30.0,8XX SEYMOUR ST,Central Business District,491251.16,5458553.29,49.279672,-123.120289
...,...,...,...,...,...,...,...,...,...,...,...,...
512790,Mischief,2003,3,25,17.0,45.0,11XX HARO ST,West End,490733.33,5459142.50,49.284964,-123.127422
512791,Break and Enter Residential/Other,2003,12,1,11.0,30.0,18XX E 37TH AVE,Kensington-Cedar Cottage,495054.00,5453768.84,49.236677,-123.067944
512792,Theft from Vehicle,2003,7,18,18.0,0.0,11XX MAINLAND ST,Central Business District,491144.35,5458003.10,49.274721,-123.121745
512793,Theft from Vehicle,2003,6,21,21.0,30.0,11XX MAINLAND ST,Central Business District,491144.35,5458003.10,49.274721,-123.121745
512794,Other Theft,2003,5,14,14.0,30.0,9XX TERMINAL AVE,Strathcona,493906.50,5457452.47,49.269802,-123.083763

In [44]:
crime_wpg = crime[crime['NEIGHBOURHOOD'] == 'West Point Grey']
# ref: https://stackoverflow.com/questions/19384532
crime_wpg.groupby('TYPE').size()
# From inspection below, the second most common is 'Break and Enter Residential/Other'

TYPE
Break and Enter Commercial                                 322
Break and Enter Residential/Other                         1252
Mischief                                                   843
Other Theft                                                251
Theft from Vehicle                                        1905
Theft of Bicycle                                           360
Theft of Vehicle                                           436
Vehicle Collision or Pedestrian Struck (with Fatality)       4
Vehicle Collision or Pedestrian Struck (with Injury)       292
dtype: int64

In [49]:
crime[crime['TYPE'] == 'Theft of Vehicle'].groupby('YEAR').size().nsmallest(2)

YEAR
2013    1034
2011    1093
dtype: int64

In [92]:
day_cond = (crime['HOUR'] >= 7) & (crime['HOUR'] < 23)
night_cond = (crime['HOUR'] < 7) | (crime['HOUR'] >= 23)

In [93]:
fatal_cond = crime['TYPE'] == 'Vehicle Collision or Pedestrian Struck (with Fatality)'
acc_cond = fatal_cond | (crime['TYPE'] == 'Vehicle Collision or Pedestrian Struck (with Injury)')

In [94]:
crime_day_fatal = crime[day_cond & fatal_cond]
crime_day_acc = crime[day_cond & acc_cond]
crime_day_rate = len(crime_day_fatal) / len(crime_day_acc)
crime_day_rate

0.009923789681451835

In [96]:
crime_night_fatal = crime[night_cond & fatal_cond]
crime_night_acc = crime[night_cond & acc_cond]
crime_night_rate = len(crime_night_fatal) / len(crime_night_acc)
crime_night_rate

0.020987654320987655

In [97]:
(crime_night_rate - crime_day_rate) * 100.0 / crime_day_rate

111.48830229861535